/**
 * Every piece of user-facing text in the app, in both languages.
 *
 * `en` is the source of truth: its keys define the `StringKey` type, and `pt`
 * is typed as a complete record of those keys, so a missing or misspelled
 * translation is a compile error rather than a blank label at runtime.
 *
 * Keys are grouped by area. Placeholders are written as {name} and filled in by
 * `t()` in ./i18n.
 *
 * Note that enum values (`active`, `checkup`, …) stay in English in data.json —
 * only their `enum.*` labels here are translated, so switching language never
 * rewrites stored records.
 */

export const en = {
  // --- common ----------------------------------------------------------------
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.saving': 'Saving…',
  'common.delete': 'Delete',
  'common.remove': 'Remove',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.loading': 'Loading…',
  'common.loadingRecords': 'Loading your records…',
  'common.notes': 'Notes',
  'common.date': 'Date',
  'common.title': 'Title',
  'common.name': 'Name',
  'common.type': 'Type',
  'common.status': 'Status',
  'common.cost': 'Cost',
  'common.costEur': 'Cost (€)',
  'common.attachments': 'Attachments',
  'common.files': 'Files',
  'common.photos': 'Photos',
  'common.vet': 'Vet',
  'common.clinic': 'Clinic',
  'common.issues': 'Issues',
  'common.relatedIssues': 'Related health issues',
  'common.open': 'Open',
  'common.print': 'Print',
  'common.startDate': 'Start date',
  'common.endDate': 'End date',
  'common.period': 'Period',
  'common.ongoing': 'ongoing',
  'common.fixFields': 'Please fix the highlighted fields.',
  'common.couldNotSave': 'Could not save',
  'common.uploadFailed': 'Upload failed',
  'common.failedLoad': 'Failed to load data',

  // --- errors & validation ---------------------------------------------------
  'error.offline': 'Cannot reach the Purrfolio server. Is `npm run dev` still running?',
  'error.requestFailed': 'Request failed ({status})',
  'validation.date': 'Expected YYYY-MM-DD',
  'validation.pet': 'A pet is required',
  'validation.name': 'Name is required',
  'validation.title': 'Title is required',
  'validation.bodyPart': 'Pick a body part',
  'validation.vaccineName': 'Vaccine name is required',
  'validation.medicationName': 'Medication name is required',
  'validation.productName': 'Product name is required',
  'validation.weightPositive': 'Weight must be greater than zero',

  // --- navigation & shell ----------------------------------------------------
  'nav.overview': 'Overview',
  'nav.records': 'Records',
  'nav.people': 'People',
  'nav.manage': 'Manage',
  'nav.dashboard': 'Dashboard',
  'nav.healthMap': 'Health map',
  'nav.appointments': 'Appointments',
  'nav.vaccinations': 'Vaccinations',
  'nav.medications': 'Medications',
  'nav.food': 'Food & diet',
  'nav.weight': 'Weight',
  'nav.journal': 'Journal',
  'nav.documents': 'Documents',
  'nav.care': 'Care & sitters',
  'nav.contacts': 'Contacts',
  'nav.pets': 'Pets',
  'nav.settings': 'Settings',
  'nav.openMenu': 'Open menu',
  'nav.closeMenu': 'Close menu',
  'nav.toggleDark': 'Toggle dark mode',
  'nav.selectedPet': 'Selected pet',
  'nav.addAPet': 'Add a pet',
  'nav.language': 'Language',

  'requirePet.title': 'No pet yet',
  'requirePet.message':
    'Add your cat (or dog, or anyone else) to start tracking their health, appointments, and everything in between.',
  'requirePet.action': 'Add your first pet',

  // --- generic resource page -------------------------------------------------
  'resource.editRecord': 'Edit record',
  'resource.deleteTitle': 'Delete this record?',
  'resource.deleteMessage': '“{name}” will be permanently removed. This cannot be undone.',

  // --- attachments -----------------------------------------------------------
  'attach.addFile': 'Add file',
  'attach.uploading': 'Uploading',
  'attach.uploadPhoto': 'Upload photo',
  'attach.change': 'Change',
  'attach.removeNamed': 'Remove {name}',
  'attach.noFile': 'No file',

  // --- issue links -----------------------------------------------------------
  'issueLinks.none': 'No health issues recorded yet — add one on the {link}.',
  'issueLinks.healthMap': 'health map',

  // --- contacts select -------------------------------------------------------
  'contactSelect.placeholder': 'Not recorded',

  // --- body map --------------------------------------------------------------
  'body.ariaLabel': 'Cat body map',
  'body.hoverHint': 'Hover a body part to inspect it',
  'body.nothingRecorded': 'nothing recorded',
  'body.activeCount': '{n} active',
  'body.resolvedCount': '{n} resolved',
  'body.titleActive.one': '{n} active issue',
  'body.titleActive.other': '{n} active issues',
  'body.titleResolved': '{n} resolved',
  'body.legendNone': 'No issues',
  'body.legendLow': 'Low',
  'body.legendMedium': 'Medium',
  'body.legendHigh': 'High',
  'body.legendResolved': 'Resolved',
  'body.offDiagram': 'Open issues not on the diagram',
  'body.leftSide': 'Left side',
  'body.rightSide': 'Right side',
  'body.organs': 'Organs',

  // --- body regions ----------------------------------------------------------
  'region.coat': 'Coat & skin',
  'region.head': 'Head',
  'region.ear': 'Ear',
  'region.eye': 'Eye',
  'region.nose': 'Nose',
  'region.mouth': 'Mouth & teeth',
  'region.neck': 'Neck & throat',
  'region.back': 'Back & spine',
  'region.chest': 'Chest',
  'region.abdomen': 'Abdomen',
  'region.hips': 'Hips',
  'region.tail': 'Tail',
  'region.front-leg-upper': 'Front leg (upper)',
  'region.front-leg-lower': 'Front leg (lower)',
  'region.front-paw': 'Front paw',
  'region.hind-leg-upper': 'Hind leg (thigh)',
  'region.hind-leg-lower': 'Hind leg (lower)',
  'region.hind-paw': 'Hind paw',
  'region.lungs': 'Lungs',
  'region.heart': 'Heart',
  'region.liver': 'Liver',
  'region.stomach': 'Stomach',
  'region.intestines': 'Intestines',
  'region.kidney': 'Kidney',
  'region.bladder': 'Bladder',
  'region.general': 'General / whole body',
  'region.behaviour': 'Behaviour & mood',

  // --- enum labels -----------------------------------------------------------
  'enum.sex.male': 'Male',
  'enum.sex.female': 'Female',
  'enum.sex.unknown': 'Unknown',

  'enum.severity.low': 'Low',
  'enum.severity.medium': 'Medium',
  'enum.severity.high': 'High',

  'enum.issueStatus.active': 'Active',
  'enum.issueStatus.monitoring': 'Monitoring',
  'enum.issueStatus.resolved': 'Resolved',

  'enum.side.left': 'Left',
  'enum.side.right': 'Right',
  'enum.side.none': 'None',

  'enum.appointmentType.checkup': 'Checkup',
  'enum.appointmentType.vaccination': 'Vaccination',
  'enum.appointmentType.surgery': 'Surgery',
  'enum.appointmentType.dental': 'Dental',
  'enum.appointmentType.emergency': 'Emergency',
  'enum.appointmentType.grooming': 'Grooming',
  'enum.appointmentType.other': 'Other',

  'enum.appointmentStatus.scheduled': 'Scheduled',
  'enum.appointmentStatus.completed': 'Completed',
  'enum.appointmentStatus.cancelled': 'Cancelled',

  'enum.medRoute.oral': 'Oral',
  'enum.medRoute.topical': 'Topical',
  'enum.medRoute.injection': 'Injection',
  'enum.medRoute.ocular': 'Ocular',
  'enum.medRoute.aural': 'Aural',
  'enum.medRoute.inhaled': 'Inhaled',
  'enum.medRoute.other': 'Other',

  'enum.foodType.dry': 'Dry',
  'enum.foodType.wet': 'Wet',
  'enum.foodType.treat': 'Treat',
  'enum.foodType.prescription': 'Prescription',
  'enum.foodType.supplement': 'Supplement',

  'enum.contactRole.vet': 'Vet',
  'enum.contactRole.clinic': 'Clinic',
  'enum.contactRole.sitter': 'Sitter',
  'enum.contactRole.groomer': 'Groomer',
  'enum.contactRole.emergency': 'Emergency',
  'enum.contactRole.other': 'Other',

  'enum.careType.sitter': 'Sitter',
  'enum.careType.boarding': 'Boarding',
  'enum.careType.travel': 'Travel',
  'enum.careType.other': 'Other',

  'enum.journalTag.behaviour': 'Behaviour',
  'enum.journalTag.litter': 'Litter',
  'enum.journalTag.grooming': 'Grooming',
  'enum.journalTag.mood': 'Mood',
  'enum.journalTag.symptom': 'Symptom',
  'enum.journalTag.milestone': 'Milestone',
  'enum.journalTag.other': 'Other',

  // --- collection names (settings page) --------------------------------------
  'collection.pets': 'Pets',
  'collection.issues': 'Issues',
  'collection.appointments': 'Appointments',
  'collection.vaccinations': 'Vaccinations',
  'collection.medications': 'Medications',
  'collection.foods': 'Foods',
  'collection.weights': 'Weigh-ins',
  'collection.careEvents': 'Care events',
  'collection.contacts': 'Contacts',
  'collection.journal': 'Journal',
  'collection.documents': 'Documents',

  // --- dates & durations -----------------------------------------------------
  'date.today': 'today',
  'date.tomorrow': 'tomorrow',
  'date.yesterday': 'yesterday',
  'age.unknown': 'Age unknown',
  'age.notBorn': 'Not born yet',
  'age.years.one': '{n} year',
  'age.years.other': '{n} years',
  'age.months.one': '{n} month',
  'age.months.other': '{n} months',

  // --- dashboard -------------------------------------------------------------
  'dash.hello': 'Hello, {name}',
  'dash.subtitle': 'Everything that needs attention, in one place.',
  'dash.neutered': 'Neutered',
  'dash.allergy': 'Allergy: {name}',
  'dash.birthday': 'Birthday {when}',
  'dash.openIssues': 'Open issues',
  'dash.nothingTracked': 'Nothing being tracked',
  'dash.vaccinationsDue': 'Vaccinations due',
  'dash.overdueCount': '{n} overdue',
  'dash.nextOn': 'Next {date}',
  'dash.allUpToDate': 'All up to date',
  'dash.activeMedication': 'Active medication',
  'dash.noneRightNow': 'None right now',
  'dash.sinceLastWeighIn': '{delta} kg since last weigh-in',
  'dash.recordedOn': 'Recorded {date}',
  'dash.noWeighIns': 'No weigh-ins yet',
  'dash.upcomingAppointments': 'Upcoming appointments',
  'dash.allAppointments': 'All appointments',
  'dash.nothingScheduled': 'Nothing scheduled.',
  'dash.noReason': 'No reason recorded',
  'dash.vaccinationsComingUp': 'Vaccinations coming up',
  'dash.allVaccinations': 'All vaccinations',
  'dash.overdue': 'Overdue',
  'dash.due': 'Due',
  'dash.careAndTimeAway': 'Care & time away',
  'dash.careSheet': 'Care sheet',
  'dash.recentActivity': 'Recent activity',
  'dash.nothingRecordedYet': 'Nothing recorded yet.',
  'dash.currentFood': 'Current food',
  'dash.allFood': 'All food',
  'dash.noCurrentFood': 'No current food recorded.',
  'dash.perDay': '{n}×/day',
  'dash.gained': 'Gained {n} kg since the previous weigh-in.',
  'dash.lost': 'Lost {n} kg since the previous weigh-in.',
  'dash.emptyTitle': 'Nothing recorded yet',
  'dash.emptyMessage':
    'Start with a vet appointment or the vaccination booklet — the dashboard fills itself in from there.',
  'dash.activityAppointment': '{type} appointment',
  'dash.activityVaccination': 'Vaccination — {name}',
  'dash.activityWeighed': 'Weighed {kg} kg',
  'dash.activityJournal': 'Journal entry',
  'dash.activityIssue': 'Issue noticed — {title}',

  // --- health map ------------------------------------------------------------
  'health.title': 'Health map',
  'health.subtitle.one': '{n} open issue for {name}. Click a body part to filter, or to record something new there.',
  'health.subtitle.other': '{n} open issues for {name}. Click a body part to filter, or to record something new there.',
  'health.newIssue': 'New issue',
  'health.filterOpen': 'Open',
  'health.filterResolved': 'Resolved',
  'health.filterAll': 'All',
  'health.clearFilter': 'Clear body part filter',
  'health.addIssueHere': 'Add issue here',
  'health.legHint': 'The near-side legs are solid; the faded ones behind belong to the {side} side.',
  'health.legHintLeft': 'left',
  'health.legHintRight': 'right',
  'health.emptySelectedTitle': 'Nothing recorded on this part',
  'health.emptyTitle': 'No issues to show',
  'health.emptySelectedMessage': '{part} has no issues.',
  'health.emptySelectedMessageOpen': '{part} has no open issues.',
  'health.emptySelectedMessageResolved': '{part} has no resolved issues.',
  'health.emptyMessage':
    'Record anything you notice — a limp, a lump, a change in appetite. Even resolved issues are worth keeping.',
  'health.firstNoticed': 'first noticed {date}',
  'health.updatesCount.one': '{n} update · last {when}',
  'health.updatesCount.other': '{n} updates · last {when}',
  'health.noUpdates': 'No progress updates yet',

  // --- issue editor ----------------------------------------------------------
  'issueEditor.editTitle': 'Edit health issue',
  'issueEditor.newTitle': 'New health issue',
  'issueEditor.saveIssue': 'Save issue',
  'issueEditor.where': 'Where is it?',
  'issueEditor.selected': 'Selected: ',
  'issueEditor.side': 'Side',
  'issueEditor.titleLabel': 'Title',
  'issueEditor.titlePlaceholder': 'Limping after jumping down',
  'issueEditor.severity': 'Severity',
  'issueEditor.status': 'Status',
  'issueEditor.firstNoticed': 'First noticed',
  'issueEditor.resolvedOn': 'Resolved on',
  'issueEditor.whatSeeing': "What you're seeing",
  'issueEditor.diagnosis': 'Diagnosis',
  'issueEditor.diagnosisHint': 'Fill this in once the vet has told you what it is.',
  'issueEditor.photosFiles': 'Photos & files',

  // --- issue detail ----------------------------------------------------------
  'issueDetail.notFound': 'Issue not found',
  'issueDetail.notFoundMessage': 'It may have been deleted.',
  'issueDetail.backToMap': 'Back to the health map',
  'issueDetail.firstNoticed': 'first noticed {date} ({rel})',
  'issueDetail.resolvedOn': ' · resolved {date}',
  'issueDetail.severityBadge': '{level} severity',
  'issueDetail.whatSeeing': "What you're seeing",
  'issueDetail.diagnosis': 'Diagnosis',
  'issueDetail.progress': 'Progress',
  'issueDetail.addUpdate': 'Add a progress update',
  'issueDetail.whatChanged': 'What changed',
  'issueDetail.updatePlaceholder': 'Swelling looks smaller, walking normally on it again.',
  'issueDetail.addUpdateAction': 'Add update',
  'issueDetail.location': 'Location',
  'issueDetail.noAppointments': 'None linked yet — link one when you {link}.',
  'issueDetail.addAppointmentLink': 'add an appointment',
  'issueDetail.noMedications': 'None linked yet.',
  'issueDetail.noDose': 'No dose recorded',
  'issueDetail.deleteTitle': 'Delete this issue?',
  'issueDetail.deleteMessage': '“{title}” and all of its progress updates will be permanently removed.',
  'issueDetail.removeUpdateTitle': 'Remove this update?',
  'issueDetail.removeUpdateMessage': 'The progress note will be deleted from the timeline.',

  // --- appointments ----------------------------------------------------------
  'appt.title': 'Appointments',
  'appt.subtitle': 'Every visit — what it was for, what came out of it, and what it cost.',
  'appt.add': 'Add appointment',
  'appt.emptyTitle': 'No appointments yet',
  'appt.emptyMessage': 'Log past visits as well as upcoming ones — the dashboard surfaces whatever is next.',
  'appt.describe': '{type} on {date}',
  'appt.when': 'When',
  'appt.reason': 'Reason',
  'appt.dateTime': 'Date & time',
  'appt.followUp': 'Follow-up date',
  'appt.weightMeasured': 'Weight measured (kg)',
  'appt.weightHint': 'Saved as a weigh-in automatically — no need to add it again under Weight.',
  'appt.reasonForVisit': 'Reason for the visit',
  'appt.reasonHint': 'Pick the health issues this visit is about — that is what keeps the issue history joined up.',
  'appt.legacyReason': 'Previously recorded as free text: “{text}”. Pick the matching issues to replace it.',
  'appt.legacyClinic': 'Previously recorded as free text: “{name}”. Pick the matching contact to replace it.',
  'appt.outcome': 'Outcome / what the vet said',
  'appt.prescribed': 'Prescribed',
  'appt.prescribedMedication': 'Medication prescribed',
  'appt.prescribedMedicationHint': 'Tick what was continued, or add what was prescribed today — it goes straight to Medications.',
  'appt.dietChange': 'Food change',
  'appt.dietChangeHint': 'Only if the vet changed the diet.',
  'appt.attachmentsHint': 'Invoices, lab results, X-rays.',

  // --- vaccinations ----------------------------------------------------------
  'vax.title': 'Vaccinations',
  'vax.subtitle': 'What was given, when, and when the next one is due.',
  'vax.add': 'Add vaccination',
  'vax.emptyTitle': 'No vaccinations recorded',
  'vax.emptyMessage':
    'Add the ones from the vaccination booklet — Purrfolio will warn you when a booster falls due.',
  'vax.vaccine': 'Vaccine',
  'vax.given': 'Given',
  'vax.nextDue': 'Next due',
  'vax.batch': 'Batch',
  'vax.overdue': 'Overdue · {when}',
  'vax.due': 'Due {when}',
  'vax.dateGiven': 'Date given',
  'vax.nextDueHint': "Leave blank if it's a one-off.",
  'vax.batchNumber': 'Batch number',
  'vax.vaccinePlaceholder': 'Rabies',
  'vax.attachmentsHint': 'Photo of the vaccination booklet page, certificate, receipt…',

  // --- medications -----------------------------------------------------------
  'med.title': 'Medications',
  'med.subtitle': "What they're on, how much, and whether today's dose has been given.",
  'med.add': 'Add medication',
  'med.emptyTitle': 'No medications recorded',
  'med.emptyMessage':
    'Add current and past prescriptions — current ones appear on the care sheet for sitters.',
  'med.logDose': 'Log a dose now',
  'med.medication': 'Medication',
  'med.dose': 'Dose',
  'med.active': 'Active',
  'med.finished': 'Finished',
  'med.lastDose': 'Last dose',
  'med.loggedCount': '{n} logged',
  'med.namePlaceholder': 'Metacam 0.5 mg/ml',
  'med.route': 'Route',
  'med.doseHint': 'Exactly as written on the label.',
  'med.dosePlaceholder': '0.5 ml',
  'med.frequency': 'Frequency',
  'med.frequencyPlaceholder': 'once daily with food',
  'med.timesPerDay': 'Times per day',
  'med.prescribedBy': 'Prescribed by',
  'med.ongoingLabel': 'Ongoing — no planned end date',
  'med.whatFor': "What it's for",
  'med.doseLog': 'Dose log ({n})',

  // --- food ------------------------------------------------------------------
  'food.title': 'Food & diet',
  'food.subtitle': 'What they eat now, what they used to eat, and how it went.',
  'food.add': 'Add food',
  'food.emptyTitle': 'No food recorded',
  'food.emptyMessage': 'Add their current food first — it becomes the feeding schedule on the care sheet.',
  'food.food': 'Food',
  'food.amount': 'Amount',
  'food.current': 'Current',
  'food.stopped': 'Stopped',
  'food.since': 'Since',
  'food.rating': 'Rating',
  'food.product': 'Product',
  'food.productPlaceholder': 'Adult Sterilised Salmon',
  'food.brand': 'Brand',
  'food.brandPlaceholder': 'Royal Canin',
  'food.amountPerDay': 'Amount per day',
  'food.amountHint': "Written the way you'd tell a sitter.",
  'food.amountPlaceholder': '55 g',
  'food.mealsPerDay': 'Meals per day',
  'food.costPerUnit': 'Cost per unit (€)',
  'food.started': 'Started',
  'food.stoppedDate': 'Stopped',
  'food.ratingLabel': 'How well they took to it (0–5)',
  'food.currentlyFeeding': 'Currently feeding this',
  'food.tolerance': 'Tolerance / reaction',
  'food.toleranceHint': 'Sickness, itching, refusal — anything worth remembering before buying it again.',
  'food.attachmentsHint': 'Photo of the label or the ingredients list.',

  // --- weight ----------------------------------------------------------------
  'weight.title': 'Weight',
  'weight.subtitleTrend': 'Currently {kg} kg, recorded {date}.',
  'weight.subtitle': 'Weigh-ins over time — the earliest sign that something is off.',
  'weight.add': 'Add weigh-in',
  'weight.emptyTitle': 'No weigh-ins yet',
  'weight.emptyMessage': 'Even a few readings a year make gradual weight loss or gain obvious.',
  'weight.describe': '{kg} kg on {date}',
  'weight.overTime': 'Weight over time',
  'weight.chartLabel': 'Weight',
  'weight.change': 'Change',
  'weight.noChange': 'no change',
  'weight.kgLabel': 'Weight (kg)',
  'weight.notesPlaceholder': 'Weighed at the clinic',
  'weight.fromAppointment': 'From an appointment',

  // --- linked records --------------------------------------------------------
  'link.create': 'Add',
  'link.addMedication': 'New medication',
  'link.addFood': 'New food',
  'link.noMedications': 'No medication recorded yet — add the first one below.',
  'link.noFoods': 'No food recorded yet — add the first one below.',

  // --- journal ---------------------------------------------------------------
  'journal.title': 'Journal',
  'journal.subtitle': "Anything that doesn't fit a form: behaviour, litter tray, sleeping, a photo from a good day.",
  'journal.add': 'Add entry',
  'journal.emptyTitle': 'Nothing written down yet',
  'journal.emptyMessage': "Small observations add up — they're often what a vet asks about first.",
  'journal.entry': 'Entry',
  'journal.tags': 'Tags',
  'journal.titlePlaceholder': 'Refused breakfast',
  'journal.whatHappened': 'What happened',

  // --- documents -------------------------------------------------------------
  'doc.title': 'Documents',
  'doc.subtitle': "Paperwork that isn't tied to a single appointment — passports, insurance, adoption papers.",
  'doc.add': 'Add document',
  'doc.emptyTitle': 'No documents stored',
  'doc.emptyMessage': 'Scan or photograph the important paperwork once and stop hunting for it.',
  'doc.category': 'Category',
  'doc.titlePlaceholder': 'Pet passport',
  'doc.suggestAdoption': 'Adoption papers',
  'doc.suggestInsurance': 'Insurance policy',
  'doc.suggestMicrochip': 'Microchip registration',
  'doc.suggestLab': 'Lab results',
  'doc.suggestPassport': 'Passport',
  'doc.suggestInvoice': 'Invoice',

  // --- care & sitters --------------------------------------------------------
  'care.title': 'Care & sitters',
  'care.subtitle': "Time away, boarding stays, and whoever is looking after them while you're gone.",
  'care.add': 'Add care period',
  'care.emptyTitle': 'No care periods planned',
  'care.emptyMessage': 'Add a holiday or a boarding stay, then print a care sheet for whoever is stepping in.',
  'care.sheetLink': 'Care sheet',
  'care.finished': 'Finished',
  'care.happeningNow': 'Happening now',
  'care.starts': 'Starts {when}',
  'care.caregiver': 'Caregiver',
  'care.emergencyContact': 'Emergency contact',
  'care.titlePlaceholder': 'Two weeks in Algarve',
  'care.caregiverHint': 'Add them under Contacts first.',
  'care.emergencyLabel': 'Emergency contact / vet to call',
  'care.instructions': 'Instructions for the caregiver',
  'care.instructionsHint':
    'Anything not already covered by food, medication or contacts — these lines appear on the care sheet.',
  'care.instructionsPlaceholder':
    'Litter tray in the laundry room, scoop daily.\nHe hides under the sofa for the first day — normal.\nSpare key with the neighbour at no. 12.',

  // --- care sheet ------------------------------------------------------------
  'sheet.back': 'Care & sitters',
  'sheet.noPeriod': 'No specific care period',
  'sheet.heading': 'Care sheet — {name}',
  'sheet.microchip': 'Microchip {number}',
  'sheet.allergiesTitle': 'Allergies — do not give',
  'sheet.feeding': 'Feeding',
  'sheet.noFood': 'No current food recorded.',
  'sheet.amountNotRecorded': 'Amount not recorded',
  'sheet.mealsADay.one': '{n} meal a day',
  'sheet.mealsADay.other': '{n} meals a day',
  'sheet.medication': 'Medication',
  'sheet.noMedication': 'No medication at the moment.',
  'sheet.medicationFor': 'For: {reason}',
  'sheet.handling': 'Handling & instructions',
  'sheet.ongoingIssues': 'Ongoing health issues to watch',
  'sheet.whoToCall': 'Who to call',
  'sheet.roleCaregiver': 'Caregiver',
  'sheet.roleEmergency': 'Emergency / vet on call',
  'sheet.noPhone': 'No phone number recorded',
  'sheet.noContacts': 'No contacts saved yet — add your vet under {link}.',
  'sheet.contactsLink': 'Contacts',
  'sheet.generated': 'Generated from Purrfolio on {date}.',

  // --- contacts --------------------------------------------------------------
  'contacts.title': 'Contacts',
  'contacts.subtitle': 'Vets, clinics, sitters and anyone else you might need in a hurry. Shared across all pets.',
  'contacts.add': 'Add contact',
  'contacts.emptyTitle': 'No contacts yet',
  'contacts.emptyMessage': 'Add your vet first — appointments and the care sheet both link to contacts.',
  'contacts.role': 'Role',
  'contacts.phone': 'Phone',
  'contacts.email': 'Email',
  'contacts.hours': 'Hours',
  'contacts.namePlaceholder': 'Dr. Ana Marques',
  'contacts.organisation': 'Organisation',
  'contacts.openingHours': 'Opening hours',
  'contacts.hoursPlaceholder': 'Mon–Fri 9–19, Sat 9–13',
  'contacts.address': 'Address',

  // --- pets ------------------------------------------------------------------
  'pets.title': 'Pets',
  'pets.subtitle': "Everyone you're keeping records for.",
  'pets.add': 'Add pet',
  'pets.emptyTitle': 'No pets yet',
  'pets.emptyMessage': 'Add your first pet to unlock the rest of the app.',
  'pets.pet': 'Pet',
  'pets.age': 'Age',
  'pets.born': 'Born',
  'pets.details': 'Details',
  'pets.neutered': 'Neutered',
  'pets.allergyCount.one': '{n} allergy',
  'pets.allergyCount.other': '{n} allergies',
  'pets.archived': 'Archived',
  'pets.photo': 'Photo',
  'pets.namePlaceholder': 'Mochi',
  'pets.species': 'Species',
  'pets.speciesPlaceholder': 'cat',
  'pets.breed': 'Breed',
  'pets.breedPlaceholder': 'Domestic shorthair',
  'pets.colour': 'Colour / markings',
  'pets.colourPlaceholder': 'Ginger tabby',
  'pets.sex': 'Sex',
  'pets.birthDate': 'Date of birth',
  'pets.birthDateHint': 'Approximate is fine — it drives the age shown everywhere.',
  'pets.adoptionDate': 'Adoption date',
  'pets.microchip': 'Microchip number',
  'pets.insurer': 'Insurer',
  'pets.policyNumber': 'Policy number',
  'pets.allergies': 'Allergies',
  'pets.allergiesHint': 'Comma separated. These are highlighted on the care sheet.',
  'pets.allergiesPlaceholder': 'chicken, dust mites',
  'pets.quirks': 'Quirks & handling notes',
  'pets.quirksHint': 'What a sitter needs to know: hiding spots, how they take pills, who they hate.',
  'pets.neuteredLabel': 'Neutered / spayed',
  'pets.archivedLabel': 'Archived (hide from the pet switcher)',

  // --- settings --------------------------------------------------------------
  'settings.title': 'Settings',
  'settings.subtitle': 'Your data lives in data/data.json inside the project folder.',
  'settings.language': 'Language',
  'settings.languageHint': 'Changes the interface only — your records are stored the same way in both languages.',
  'settings.backupTitle': 'Backup & restore',
  'settings.backupText':
    'A snapshot is taken automatically before every save — the last 20 are kept. You can also export a copy to keep somewhere else.',
  'settings.exportJson': 'Export JSON',
  'settings.importJson': 'Import JSON',
  'settings.storedTitle': "What's stored",
  'settings.snapshotsTitle': 'Automatic snapshots',
  'settings.noSnapshots': 'No snapshots yet — they appear after your first save.',
  'settings.restore': 'Restore',
  'settings.invalidJson': "That file isn't valid JSON.",
  'settings.imported': 'Data imported. The previous version was saved as a backup.',
  'settings.importFailed': 'Import failed',
  'settings.restored': 'Restored the snapshot from {date}.',
  'settings.restoreFailed': 'Restore failed',
  'settings.replaceTitle': 'Replace all data?',
  'settings.replaceMessage':
    'Everything currently stored will be replaced by the contents of that file. A snapshot of the current data is saved first, so this is reversible.',
  'settings.import': 'Import',
  'settings.restoreTitle': 'Restore this snapshot?',
  'settings.restoreMessage': 'Your data will be rolled back to {date}. The current state is snapshotted first.',
} as const;

export type StringKey = keyof typeof en;

export const pt: Record<StringKey, string> = {
  // --- comum -----------------------------------------------------------------
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.saving': 'A guardar…',
  'common.delete': 'Eliminar',
  'common.remove': 'Remover',
  'common.edit': 'Editar',
  'common.close': 'Fechar',
  'common.loading': 'A carregar…',
  'common.loadingRecords': 'A carregar os registos…',
  'common.notes': 'Notas',
  'common.date': 'Data',
  'common.title': 'Título',
  'common.name': 'Nome',
  'common.type': 'Tipo',
  'common.status': 'Estado',
  'common.cost': 'Custo',
  'common.costEur': 'Custo (€)',
  'common.attachments': 'Anexos',
  'common.files': 'Ficheiros',
  'common.photos': 'Fotografias',
  'common.vet': 'Veterinário',
  'common.clinic': 'Clínica',
  'common.issues': 'Problemas',
  'common.relatedIssues': 'Problemas de saúde relacionados',
  'common.open': 'Abrir',
  'common.print': 'Imprimir',
  'common.startDate': 'Data de início',
  'common.endDate': 'Data de fim',
  'common.period': 'Período',
  'common.ongoing': 'em curso',
  'common.fixFields': 'Corrija os campos assinalados.',
  'common.couldNotSave': 'Não foi possível guardar',
  'common.uploadFailed': 'Falha ao carregar o ficheiro',
  'common.failedLoad': 'Não foi possível carregar os dados',

  // --- erros e validação -----------------------------------------------------
  'error.offline': 'Não é possível contactar o servidor do Purrfolio. O `npm run dev` ainda está a correr?',
  'error.requestFailed': 'O pedido falhou ({status})',
  'validation.date': 'Formato esperado: AAAA-MM-DD',
  'validation.pet': 'É necessário indicar um animal',
  'validation.name': 'O nome é obrigatório',
  'validation.title': 'O título é obrigatório',
  'validation.bodyPart': 'Escolha uma zona do corpo',
  'validation.vaccineName': 'O nome da vacina é obrigatório',
  'validation.medicationName': 'O nome do medicamento é obrigatório',
  'validation.productName': 'O nome do produto é obrigatório',
  'validation.weightPositive': 'O peso tem de ser maior do que zero',

  // --- navegação -------------------------------------------------------------
  'nav.overview': 'Visão geral',
  'nav.records': 'Registos',
  'nav.people': 'Pessoas',
  'nav.manage': 'Gerir',
  'nav.dashboard': 'Painel',
  'nav.healthMap': 'Mapa de saúde',
  'nav.appointments': 'Consultas',
  'nav.vaccinations': 'Vacinas',
  'nav.medications': 'Medicação',
  'nav.food': 'Alimentação',
  'nav.weight': 'Peso',
  'nav.journal': 'Diário',
  'nav.documents': 'Documentos',
  'nav.care': 'Cuidados e ama',
  'nav.contacts': 'Contactos',
  'nav.pets': 'Animais',
  'nav.settings': 'Definições',
  'nav.openMenu': 'Abrir menu',
  'nav.closeMenu': 'Fechar menu',
  'nav.toggleDark': 'Alternar modo escuro',
  'nav.selectedPet': 'Animal selecionado',
  'nav.addAPet': 'Adicionar animal',
  'nav.language': 'Idioma',

  'requirePet.title': 'Ainda não há animais',
  'requirePet.message':
    'Adicione o seu gato (ou cão, ou quem quer que seja) para começar a registar a saúde, as consultas e tudo o resto.',
  'requirePet.action': 'Adicionar o primeiro animal',

  // --- página de recursos ----------------------------------------------------
  'resource.editRecord': 'Editar registo',
  'resource.deleteTitle': 'Eliminar este registo?',
  'resource.deleteMessage': '“{name}” será removido definitivamente. Esta ação não pode ser anulada.',

  // --- anexos ----------------------------------------------------------------
  'attach.addFile': 'Adicionar',
  'attach.uploading': 'A carregar',
  'attach.uploadPhoto': 'Carregar foto',
  'attach.change': 'Alterar',
  'attach.removeNamed': 'Remover {name}',
  'attach.noFile': 'Sem ficheiro',

  // --- ligações a problemas --------------------------------------------------
  'issueLinks.none': 'Ainda não há problemas de saúde registados — adicione um no {link}.',
  'issueLinks.healthMap': 'mapa de saúde',

  // --- seletor de contactos --------------------------------------------------
  'contactSelect.placeholder': 'Não indicado',

  // --- mapa corporal ---------------------------------------------------------
  'body.ariaLabel': 'Mapa corporal do gato',
  'body.hoverHint': 'Passe o rato sobre uma zona para a inspecionar',
  'body.nothingRecorded': 'nada registado',
  'body.activeCount': '{n} ativos',
  'body.resolvedCount': '{n} resolvidos',
  'body.titleActive.one': '{n} problema ativo',
  'body.titleActive.other': '{n} problemas ativos',
  'body.titleResolved': '{n} resolvidos',
  'body.legendNone': 'Sem problemas',
  'body.legendLow': 'Baixa',
  'body.legendMedium': 'Média',
  'body.legendHigh': 'Alta',
  'body.legendResolved': 'Resolvido',
  'body.offDiagram': 'Problemas em aberto fora do diagrama',
  'body.leftSide': 'Lado esquerdo',
  'body.rightSide': 'Lado direito',
  'body.organs': 'Órgãos',

  // --- zonas do corpo --------------------------------------------------------
  'region.coat': 'Pelagem e pele',
  'region.head': 'Cabeça',
  'region.ear': 'Orelha',
  'region.eye': 'Olho',
  'region.nose': 'Nariz',
  'region.mouth': 'Boca e dentes',
  'region.neck': 'Pescoço e garganta',
  'region.back': 'Costas e coluna',
  'region.chest': 'Peito',
  'region.abdomen': 'Abdómen',
  'region.hips': 'Ancas',
  'region.tail': 'Cauda',
  'region.front-leg-upper': 'Perna dianteira superior',
  'region.front-leg-lower': 'Perna dianteira inferior',
  'region.front-paw': 'Pata dianteira',
  'region.hind-leg-upper': 'Coxa traseira',
  'region.hind-leg-lower': 'Perna traseira inferior',
  'region.hind-paw': 'Pata traseira',
  'region.lungs': 'Pulmões',
  'region.heart': 'Coração',
  'region.liver': 'Fígado',
  'region.stomach': 'Estômago',
  'region.intestines': 'Intestinos',
  'region.kidney': 'Rim',
  'region.bladder': 'Bexiga',
  'region.general': 'Geral / corpo inteiro',
  'region.behaviour': 'Comportamento e humor',

  // --- valores de listas -----------------------------------------------------
  'enum.sex.male': 'Macho',
  'enum.sex.female': 'Fêmea',
  'enum.sex.unknown': 'Desconhecido',

  'enum.severity.low': 'Baixa',
  'enum.severity.medium': 'Média',
  'enum.severity.high': 'Alta',

  'enum.issueStatus.active': 'Ativo',
  'enum.issueStatus.monitoring': 'Em observação',
  'enum.issueStatus.resolved': 'Resolvido',

  'enum.side.left': 'Esquerdo',
  'enum.side.right': 'Direito',
  'enum.side.none': 'Nenhum',

  'enum.appointmentType.checkup': 'Consulta de rotina',
  'enum.appointmentType.vaccination': 'Vacinação',
  'enum.appointmentType.surgery': 'Cirurgia',
  'enum.appointmentType.dental': 'Dentária',
  'enum.appointmentType.emergency': 'Urgência',
  'enum.appointmentType.grooming': 'Banho e tosquia',
  'enum.appointmentType.other': 'Outra',

  'enum.appointmentStatus.scheduled': 'Agendada',
  'enum.appointmentStatus.completed': 'Concluída',
  'enum.appointmentStatus.cancelled': 'Cancelada',

  'enum.medRoute.oral': 'Oral',
  'enum.medRoute.topical': 'Tópica',
  'enum.medRoute.injection': 'Injeção',
  'enum.medRoute.ocular': 'Ocular',
  'enum.medRoute.aural': 'Auricular',
  'enum.medRoute.inhaled': 'Inalada',
  'enum.medRoute.other': 'Outra',

  'enum.foodType.dry': 'Seca',
  'enum.foodType.wet': 'Húmida',
  'enum.foodType.treat': 'Snack',
  'enum.foodType.prescription': 'Dieta médica',
  'enum.foodType.supplement': 'Suplemento',

  'enum.contactRole.vet': 'Veterinário',
  'enum.contactRole.clinic': 'Clínica',
  'enum.contactRole.sitter': 'Ama',
  'enum.contactRole.groomer': 'Tosquiador',
  'enum.contactRole.emergency': 'Urgência',
  'enum.contactRole.other': 'Outro',

  'enum.careType.sitter': 'Ama',
  'enum.careType.boarding': 'Hotel',
  'enum.careType.travel': 'Viagem',
  'enum.careType.other': 'Outro',

  'enum.journalTag.behaviour': 'Comportamento',
  'enum.journalTag.litter': 'Caixa de areia',
  'enum.journalTag.grooming': 'Higiene',
  'enum.journalTag.mood': 'Humor',
  'enum.journalTag.symptom': 'Sintoma',
  'enum.journalTag.milestone': 'Marco',
  'enum.journalTag.other': 'Outro',

  // --- coleções --------------------------------------------------------------
  'collection.pets': 'Animais',
  'collection.issues': 'Problemas',
  'collection.appointments': 'Consultas',
  'collection.vaccinations': 'Vacinas',
  'collection.medications': 'Medicação',
  'collection.foods': 'Alimentos',
  'collection.weights': 'Pesagens',
  'collection.careEvents': 'Períodos de cuidados',
  'collection.contacts': 'Contactos',
  'collection.journal': 'Diário',
  'collection.documents': 'Documentos',

  // --- datas -----------------------------------------------------------------
  'date.today': 'hoje',
  'date.tomorrow': 'amanhã',
  'date.yesterday': 'ontem',
  'age.unknown': 'Idade desconhecida',
  'age.notBorn': 'Ainda não nasceu',
  'age.years.one': '{n} ano',
  'age.years.other': '{n} anos',
  'age.months.one': '{n} mês',
  'age.months.other': '{n} meses',

  // --- painel ----------------------------------------------------------------
  'dash.hello': 'Olá, {name}',
  'dash.subtitle': 'Tudo o que precisa de atenção, num só sítio.',
  'dash.neutered': 'Castrado',
  'dash.allergy': 'Alergia: {name}',
  'dash.birthday': 'Aniversário {when}',
  'dash.openIssues': 'Problemas em aberto',
  'dash.nothingTracked': 'Nada em acompanhamento',
  'dash.vaccinationsDue': 'Vacinas a vencer',
  'dash.overdueCount': '{n} em atraso',
  'dash.nextOn': 'Próxima {date}',
  'dash.allUpToDate': 'Tudo em dia',
  'dash.activeMedication': 'Medicação ativa',
  'dash.noneRightNow': 'Nenhuma de momento',
  'dash.sinceLastWeighIn': '{delta} kg desde a última pesagem',
  'dash.recordedOn': 'Registado {date}',
  'dash.noWeighIns': 'Ainda sem pesagens',
  'dash.upcomingAppointments': 'Próximas consultas',
  'dash.allAppointments': 'Todas as consultas',
  'dash.nothingScheduled': 'Nada agendado.',
  'dash.noReason': 'Sem motivo registado',
  'dash.vaccinationsComingUp': 'Vacinas a chegar',
  'dash.allVaccinations': 'Todas as vacinas',
  'dash.overdue': 'Em atraso',
  'dash.due': 'A vencer',
  'dash.careAndTimeAway': 'Cuidados e ausências',
  'dash.careSheet': 'Ficha de cuidados',
  'dash.recentActivity': 'Atividade recente',
  'dash.nothingRecordedYet': 'Ainda não há nada registado.',
  'dash.currentFood': 'Alimentação atual',
  'dash.allFood': 'Toda a alimentação',
  'dash.noCurrentFood': 'Sem alimentação atual registada.',
  'dash.perDay': '{n}×/dia',
  'dash.gained': 'Ganhou {n} kg desde a pesagem anterior.',
  'dash.lost': 'Perdeu {n} kg desde a pesagem anterior.',
  'dash.emptyTitle': 'Ainda não há nada registado',
  'dash.emptyMessage':
    'Comece por uma consulta ou pelo boletim de vacinas — o painel preenche-se a partir daí.',
  'dash.activityAppointment': 'Consulta: {type}',
  'dash.activityVaccination': 'Vacina — {name}',
  'dash.activityWeighed': 'Pesou {kg} kg',
  'dash.activityJournal': 'Entrada no diário',
  'dash.activityIssue': 'Problema detetado — {title}',

  // --- mapa de saúde ---------------------------------------------------------
  'health.title': 'Mapa de saúde',
  'health.subtitle.one':
    '{n} problema em aberto para {name}. Clique numa zona do corpo para filtrar ou para registar algo novo aí.',
  'health.subtitle.other':
    '{n} problemas em aberto para {name}. Clique numa zona do corpo para filtrar ou para registar algo novo aí.',
  'health.newIssue': 'Novo problema',
  'health.filterOpen': 'Em aberto',
  'health.filterResolved': 'Resolvidos',
  'health.filterAll': 'Todos',
  'health.clearFilter': 'Limpar filtro de zona do corpo',
  'health.addIssueHere': 'Adicionar problema aqui',
  'health.legHint': 'As patas do lado próximo estão a cheio; as esbatidas atrás pertencem ao lado {side}.',
  'health.legHintLeft': 'esquerdo',
  'health.legHintRight': 'direito',
  'health.emptySelectedTitle': 'Nada registado nesta zona',
  'health.emptyTitle': 'Sem problemas a mostrar',
  'health.emptySelectedMessage': '{part} não tem problemas.',
  'health.emptySelectedMessageOpen': '{part} não tem problemas em aberto.',
  'health.emptySelectedMessageResolved': '{part} não tem problemas resolvidos.',
  'health.emptyMessage':
    'Registe tudo o que notar — um coxear, um caroço, uma mudança de apetite. Até os problemas resolvidos vale a pena guardar.',
  'health.firstNoticed': 'notado a {date}',
  'health.updatesCount.one': '{n} atualização · última {when}',
  'health.updatesCount.other': '{n} atualizações · última {when}',
  'health.noUpdates': 'Ainda sem atualizações',

  // --- editor de problemas ---------------------------------------------------
  'issueEditor.editTitle': 'Editar problema de saúde',
  'issueEditor.newTitle': 'Novo problema de saúde',
  'issueEditor.saveIssue': 'Guardar problema',
  'issueEditor.where': 'Onde é?',
  'issueEditor.selected': 'Selecionado: ',
  'issueEditor.side': 'Lado',
  'issueEditor.titleLabel': 'Título',
  'issueEditor.titlePlaceholder': 'Coxear depois de saltar',
  'issueEditor.severity': 'Gravidade',
  'issueEditor.status': 'Estado',
  'issueEditor.firstNoticed': 'Notado a',
  'issueEditor.resolvedOn': 'Resolvido a',
  'issueEditor.whatSeeing': 'O que está a observar',
  'issueEditor.diagnosis': 'Diagnóstico',
  'issueEditor.diagnosisHint': 'Preencha assim que o veterinário disser o que é.',
  'issueEditor.photosFiles': 'Fotografias e ficheiros',

  // --- detalhe do problema ---------------------------------------------------
  'issueDetail.notFound': 'Problema não encontrado',
  'issueDetail.notFoundMessage': 'Pode ter sido eliminado.',
  'issueDetail.backToMap': 'Voltar ao mapa de saúde',
  'issueDetail.firstNoticed': 'notado a {date} ({rel})',
  'issueDetail.resolvedOn': ' · resolvido a {date}',
  'issueDetail.severityBadge': 'Gravidade {level}',
  'issueDetail.whatSeeing': 'O que está a observar',
  'issueDetail.diagnosis': 'Diagnóstico',
  'issueDetail.progress': 'Evolução',
  'issueDetail.addUpdate': 'Adicionar uma atualização',
  'issueDetail.whatChanged': 'O que mudou',
  'issueDetail.updatePlaceholder': 'O inchaço parece menor, já anda normalmente.',
  'issueDetail.addUpdateAction': 'Adicionar',
  'issueDetail.location': 'Localização',
  'issueDetail.noAppointments': 'Ainda sem ligações — associe uma quando {link}.',
  'issueDetail.addAppointmentLink': 'adicionar uma consulta',
  'issueDetail.noMedications': 'Ainda sem ligações.',
  'issueDetail.noDose': 'Sem dose registada',
  'issueDetail.deleteTitle': 'Eliminar este problema?',
  'issueDetail.deleteMessage': '“{title}” e todas as suas atualizações serão removidos definitivamente.',
  'issueDetail.removeUpdateTitle': 'Remover esta atualização?',
  'issueDetail.removeUpdateMessage': 'A nota de evolução será eliminada da cronologia.',

  // --- consultas -------------------------------------------------------------
  'appt.title': 'Consultas',
  'appt.subtitle': 'Todas as visitas — o motivo, o resultado e quanto custou.',
  'appt.add': 'Adicionar consulta',
  'appt.emptyTitle': 'Ainda não há consultas',
  'appt.emptyMessage': 'Registe também as visitas passadas — o painel mostra sempre a próxima.',
  'appt.describe': '{type} a {date}',
  'appt.when': 'Quando',
  'appt.reason': 'Motivo',
  'appt.dateTime': 'Data e hora',
  'appt.followUp': 'Data de reavaliação',
  'appt.weightMeasured': 'Peso medido (kg)',
  'appt.weightHint': 'Fica guardado como pesagem automaticamente — não precisa de o repetir em Peso.',
  'appt.reasonForVisit': 'Motivo da consulta',
  'appt.reasonHint': 'Escolha os problemas de saúde a que esta consulta diz respeito — é assim que o histórico fica ligado.',
  'appt.legacyReason': 'Estava registado como texto livre: «{text}». Escolha os problemas correspondentes para o substituir.',
  'appt.legacyClinic': 'Estava registado como texto livre: «{name}». Escolha o contacto correspondente para o substituir.',
  'appt.outcome': 'Resultado / o que disse o veterinário',
  'appt.prescribed': 'Prescrito',
  'appt.prescribedMedication': 'Medicação prescrita',
  'appt.prescribedMedicationHint': 'Marque o que se mantém, ou acrescente o que foi prescrito hoje — vai direto para Medicação.',
  'appt.dietChange': 'Alteração de alimentação',
  'appt.dietChangeHint': 'Só se o veterinário tiver mudado a dieta.',
  'appt.attachmentsHint': 'Faturas, análises, radiografias.',

  // --- vacinas ---------------------------------------------------------------
  'vax.title': 'Vacinas',
  'vax.subtitle': 'O que foi administrado, quando, e quando é a próxima.',
  'vax.add': 'Adicionar vacina',
  'vax.emptyTitle': 'Sem vacinas registadas',
  'vax.emptyMessage':
    'Adicione as do boletim de vacinas — o Purrfolio avisa quando um reforço estiver a vencer.',
  'vax.vaccine': 'Vacina',
  'vax.given': 'Administrada',
  'vax.nextDue': 'Próxima',
  'vax.batch': 'Lote',
  'vax.overdue': 'Em atraso · {when}',
  'vax.due': 'A vencer {when}',
  'vax.dateGiven': 'Data de administração',
  'vax.nextDueHint': 'Deixe em branco se for dose única.',
  'vax.batchNumber': 'Número do lote',
  'vax.vaccinePlaceholder': 'Raiva',
  'vax.attachmentsHint': 'Foto da página do boletim, certificado, recibo…',

  // --- medicação -------------------------------------------------------------
  'med.title': 'Medicação',
  'med.subtitle': 'O que está a tomar, quanto, e se a dose de hoje já foi dada.',
  'med.add': 'Adicionar medicamento',
  'med.emptyTitle': 'Sem medicação registada',
  'med.emptyMessage':
    'Adicione as prescrições atuais e passadas — as atuais aparecem na ficha de cuidados para a ama.',
  'med.logDose': 'Registar uma dose agora',
  'med.medication': 'Medicamento',
  'med.dose': 'Dose',
  'med.active': 'Ativo',
  'med.finished': 'Terminado',
  'med.lastDose': 'Última dose',
  'med.loggedCount': '{n} registadas',
  'med.namePlaceholder': 'Metacam 0,5 mg/ml',
  'med.route': 'Via',
  'med.doseHint': 'Exatamente como está escrito no rótulo.',
  'med.dosePlaceholder': '0,5 ml',
  'med.frequency': 'Frequência',
  'med.frequencyPlaceholder': 'uma vez por dia com comida',
  'med.timesPerDay': 'Vezes por dia',
  'med.prescribedBy': 'Prescrito por',
  'med.ongoingLabel': 'Em curso — sem data de fim prevista',
  'med.whatFor': 'Para que serve',
  'med.doseLog': 'Registo de doses ({n})',

  // --- alimentação -----------------------------------------------------------
  'food.title': 'Alimentação',
  'food.subtitle': 'O que come agora, o que comia antes, e como correu.',
  'food.add': 'Adicionar alimento',
  'food.emptyTitle': 'Sem alimentação registada',
  'food.emptyMessage':
    'Comece pela alimentação atual — passa a ser o plano de refeições da ficha de cuidados.',
  'food.food': 'Alimento',
  'food.amount': 'Quantidade',
  'food.current': 'Atual',
  'food.stopped': 'Descontinuado',
  'food.since': 'Desde',
  'food.rating': 'Avaliação',
  'food.product': 'Produto',
  'food.productPlaceholder': 'Adult Sterilised Salmon',
  'food.brand': 'Marca',
  'food.brandPlaceholder': 'Royal Canin',
  'food.amountPerDay': 'Quantidade por dia',
  'food.amountHint': 'Escrita como a diria a quem fica com ele.',
  'food.amountPlaceholder': '55 g',
  'food.mealsPerDay': 'Refeições por dia',
  'food.costPerUnit': 'Custo por unidade (€)',
  'food.started': 'Início',
  'food.stoppedDate': 'Fim',
  'food.ratingLabel': 'Como aceitou (0–5)',
  'food.currentlyFeeding': 'É o que come atualmente',
  'food.tolerance': 'Tolerância / reação',
  'food.toleranceHint': 'Vómitos, comichão, recusa — algo que valha a pena lembrar antes de comprar outra vez.',
  'food.attachmentsHint': 'Foto do rótulo ou da lista de ingredientes.',

  // --- peso ------------------------------------------------------------------
  'weight.title': 'Peso',
  'weight.subtitleTrend': 'Atualmente {kg} kg, registado a {date}.',
  'weight.subtitle': 'Pesagens ao longo do tempo — o primeiro sinal de que algo não está bem.',
  'weight.add': 'Adicionar pesagem',
  'weight.emptyTitle': 'Ainda sem pesagens',
  'weight.emptyMessage': 'Mesmo poucas medições por ano tornam óbvia a perda ou o ganho gradual de peso.',
  'weight.describe': '{kg} kg a {date}',
  'weight.overTime': 'Peso ao longo do tempo',
  'weight.chartLabel': 'Peso',
  'weight.change': 'Variação',
  'weight.noChange': 'sem alteração',
  'weight.kgLabel': 'Peso (kg)',
  'weight.notesPlaceholder': 'Pesado na clínica',
  'weight.fromAppointment': 'Da consulta',

  // --- registos ligados ------------------------------------------------------
  'link.create': 'Adicionar',
  'link.addMedication': 'Nova medicação',
  'link.addFood': 'Novo alimento',
  'link.noMedications': 'Ainda não há medicação registada — adicione a primeira abaixo.',
  'link.noFoods': 'Ainda não há alimentação registada — adicione a primeira abaixo.',

  // --- diário ----------------------------------------------------------------
  'journal.title': 'Diário',
  'journal.subtitle':
    'Tudo o que não cabe num formulário: comportamento, caixa de areia, sono, uma foto de um bom dia.',
  'journal.add': 'Adicionar entrada',
  'journal.emptyTitle': 'Ainda não há nada escrito',
  'journal.emptyMessage':
    'As pequenas observações somam-se — são muitas vezes a primeira coisa que o veterinário pergunta.',
  'journal.entry': 'Entrada',
  'journal.tags': 'Etiquetas',
  'journal.titlePlaceholder': 'Recusou o pequeno-almoço',
  'journal.whatHappened': 'O que aconteceu',

  // --- documentos ------------------------------------------------------------
  'doc.title': 'Documentos',
  'doc.subtitle':
    'Papelada que não está ligada a uma consulta — passaportes, seguros, papéis de adoção.',
  'doc.add': 'Adicionar documento',
  'doc.emptyTitle': 'Sem documentos guardados',
  'doc.emptyMessage': 'Digitalize ou fotografe a papelada importante uma vez e deixe de andar à procura dela.',
  'doc.category': 'Categoria',
  'doc.titlePlaceholder': 'Passaporte do animal',
  'doc.suggestAdoption': 'Papéis de adoção',
  'doc.suggestInsurance': 'Apólice de seguro',
  'doc.suggestMicrochip': 'Registo do microchip',
  'doc.suggestLab': 'Análises',
  'doc.suggestPassport': 'Passaporte',
  'doc.suggestInvoice': 'Fatura',

  // --- cuidados e ama --------------------------------------------------------
  'care.title': 'Cuidados e ama',
  'care.subtitle': 'Ausências, estadias em hotel, e quem fica a tomar conta enquanto está fora.',
  'care.add': 'Adicionar período',
  'care.emptyTitle': 'Sem períodos de cuidados planeados',
  'care.emptyMessage':
    'Adicione umas férias ou uma estadia em hotel e imprima uma ficha de cuidados para quem ficar responsável.',
  'care.sheetLink': 'Ficha de cuidados',
  'care.finished': 'Terminado',
  'care.happeningNow': 'A decorrer',
  'care.starts': 'Começa {when}',
  'care.caregiver': 'Responsável',
  'care.emergencyContact': 'Contacto de urgência',
  'care.titlePlaceholder': 'Duas semanas no Algarve',
  'care.caregiverHint': 'Adicione-o primeiro em Contactos.',
  'care.emergencyLabel': 'Contacto de urgência / veterinário a chamar',
  'care.instructions': 'Instruções para o responsável',
  'care.instructionsHint':
    'Tudo o que não esteja já coberto pela alimentação, medicação ou contactos — estas linhas aparecem na ficha de cuidados.',
  'care.instructionsPlaceholder':
    'Caixa de areia na lavandaria, limpar todos os dias.\nEsconde-se debaixo do sofá no primeiro dia — é normal.\nChave suplente com a vizinha do n.º 12.',

  // --- ficha de cuidados -----------------------------------------------------
  'sheet.back': 'Cuidados e ama',
  'sheet.noPeriod': 'Sem período específico',
  'sheet.heading': 'Ficha de cuidados — {name}',
  'sheet.microchip': 'Microchip {number}',
  'sheet.allergiesTitle': 'Alergias — não dar',
  'sheet.feeding': 'Alimentação',
  'sheet.noFood': 'Sem alimentação atual registada.',
  'sheet.amountNotRecorded': 'Quantidade não registada',
  'sheet.mealsADay.one': '{n} refeição por dia',
  'sheet.mealsADay.other': '{n} refeições por dia',
  'sheet.medication': 'Medicação',
  'sheet.noMedication': 'Sem medicação de momento.',
  'sheet.medicationFor': 'Para: {reason}',
  'sheet.handling': 'Maneio e instruções',
  'sheet.ongoingIssues': 'Problemas de saúde a vigiar',
  'sheet.whoToCall': 'Quem contactar',
  'sheet.roleCaregiver': 'Responsável',
  'sheet.roleEmergency': 'Urgência / veterinário de serviço',
  'sheet.noPhone': 'Sem número de telefone registado',
  'sheet.noContacts': 'Ainda não há contactos — adicione o seu veterinário em {link}.',
  'sheet.contactsLink': 'Contactos',
  'sheet.generated': 'Gerado pelo Purrfolio a {date}.',

  // --- contactos -------------------------------------------------------------
  'contacts.title': 'Contactos',
  'contacts.subtitle':
    'Veterinários, clínicas, amas e quem mais possa ser preciso à pressa. Partilhados por todos os animais.',
  'contacts.add': 'Adicionar contacto',
  'contacts.emptyTitle': 'Ainda não há contactos',
  'contacts.emptyMessage':
    'Comece pelo seu veterinário — as consultas e a ficha de cuidados ligam-se aos contactos.',
  'contacts.role': 'Função',
  'contacts.phone': 'Telefone',
  'contacts.email': 'E-mail',
  'contacts.hours': 'Horário',
  'contacts.namePlaceholder': 'Dra. Ana Marques',
  'contacts.organisation': 'Organização',
  'contacts.openingHours': 'Horário de funcionamento',
  'contacts.hoursPlaceholder': 'Seg–Sex 9–19, Sáb 9–13',
  'contacts.address': 'Morada',

  // --- animais ---------------------------------------------------------------
  'pets.title': 'Animais',
  'pets.subtitle': 'Todos aqueles de quem guarda registos.',
  'pets.add': 'Adicionar animal',
  'pets.emptyTitle': 'Ainda não há animais',
  'pets.emptyMessage': 'Adicione o primeiro animal para desbloquear o resto da aplicação.',
  'pets.pet': 'Animal',
  'pets.age': 'Idade',
  'pets.born': 'Nascimento',
  'pets.details': 'Detalhes',
  'pets.neutered': 'Castrado',
  'pets.allergyCount.one': '{n} alergia',
  'pets.allergyCount.other': '{n} alergias',
  'pets.archived': 'Arquivado',
  'pets.photo': 'Fotografia',
  'pets.namePlaceholder': 'Mochi',
  'pets.species': 'Espécie',
  'pets.speciesPlaceholder': 'gato',
  'pets.breed': 'Raça',
  'pets.breedPlaceholder': 'Europeu comum',
  'pets.colour': 'Cor / marcas',
  'pets.colourPlaceholder': 'Ruivo malhado',
  'pets.sex': 'Sexo',
  'pets.birthDate': 'Data de nascimento',
  'pets.birthDateHint': 'Aproximada chega — é o que define a idade mostrada em todo o lado.',
  'pets.adoptionDate': 'Data de adoção',
  'pets.microchip': 'Número do microchip',
  'pets.insurer': 'Seguradora',
  'pets.policyNumber': 'Número da apólice',
  'pets.allergies': 'Alergias',
  'pets.allergiesHint': 'Separadas por vírgulas. Aparecem destacadas na ficha de cuidados.',
  'pets.allergiesPlaceholder': 'frango, ácaros',
  'pets.quirks': 'Manias e notas de maneio',
  'pets.quirksHint': 'O que uma ama precisa de saber: onde se esconde, como toma comprimidos, de quem não gosta.',
  'pets.neuteredLabel': 'Castrado / esterilizado',
  'pets.archivedLabel': 'Arquivado (esconder do seletor de animais)',

  // --- definições ------------------------------------------------------------
  'settings.title': 'Definições',
  'settings.subtitle': 'Os seus dados estão em data/data.json, dentro da pasta do projeto.',
  'settings.language': 'Idioma',
  'settings.languageHint':
    'Muda apenas a interface — os registos são guardados da mesma forma nos dois idiomas.',
  'settings.backupTitle': 'Cópias de segurança',
  'settings.backupText':
    'É guardada uma cópia automaticamente antes de cada gravação — ficam as últimas 20. Também pode exportar uma cópia para guardar noutro sítio.',
  'settings.exportJson': 'Exportar JSON',
  'settings.importJson': 'Importar JSON',
  'settings.storedTitle': 'O que está guardado',
  'settings.snapshotsTitle': 'Cópias automáticas',
  'settings.noSnapshots': 'Ainda não há cópias — aparecem depois da primeira gravação.',
  'settings.restore': 'Repor',
  'settings.invalidJson': 'Esse ficheiro não é JSON válido.',
  'settings.imported': 'Dados importados. A versão anterior foi guardada como cópia de segurança.',
  'settings.importFailed': 'A importação falhou',
  'settings.restored': 'Reposta a cópia de {date}.',
  'settings.restoreFailed': 'A reposição falhou',
  'settings.replaceTitle': 'Substituir todos os dados?',
  'settings.replaceMessage':
    'Tudo o que está guardado será substituído pelo conteúdo desse ficheiro. É guardada primeiro uma cópia dos dados atuais, por isso é reversível.',
  'settings.import': 'Importar',
  'settings.restoreTitle': 'Repor esta cópia?',
  'settings.restoreMessage': 'Os seus dados voltam ao estado de {date}. O estado atual é guardado primeiro.',
};

/**
 * Grammatical gender of each body region in Portuguese, so `describePart` can
 * agree the side adjective with the noun: 'Olho esquerdo' but 'Pata esquerda'.
 * English ignores this entirely.
 */
export const PT_REGION_GENDER: Record<string, 'm' | 'f'> = {
  coat: 'f',
  head: 'f',
  ear: 'f',
  eye: 'm',
  nose: 'm',
  mouth: 'f',
  neck: 'm',
  back: 'f',
  chest: 'm',
  abdomen: 'm',
  hips: 'f',
  tail: 'f',
  'front-leg-upper': 'f',
  'front-leg-lower': 'f',
  'front-paw': 'f',
  'hind-leg-upper': 'f',
  'hind-leg-lower': 'f',
  'hind-paw': 'f',
  lungs: 'm',
  heart: 'm',
  liver: 'm',
  stomach: 'm',
  intestines: 'm',
  kidney: 'm',
  bladder: 'f',
  general: 'm',
  behaviour: 'm',
};
